openapi: 3.0.0
info:
  title: Agent Component Specification
  description: Defines the attributes of different agent components such as Tools, LLMs, Local Memory, Guardrails, Monitors, and Orchestrators.
  version: 1.0.0

components:
  schemas:
    AgentComponent:
      type: object
      required:
        - id
        - name
        - kind
        - version
      properties:
        id:
          type: string
          description: Unique identifier for the component.
          example: urn:component:my_domain:tool:1
        name:
          type: string
          description: Human-readable name of the component.
          example: Trade Execution Tool
        kind:
          type: string
          description: Type of component (e.g., Tool, LLM, Memory, Guardrail, Monitor, Orchestrator).
          enum:
            - Tool
            - LLM
            - Memory
            - Guardrail
            - Monitor
            - Orchestrator
          example: Tool
        version:
          type: string
          description: Version of the component.
          example: 1.0.0
        description:
          type: string
          description: Describes the component’s purpose and role.
          example: Executes trades via Interactive Brokers API.
        dependencies:
          type: array
          description: List of other components or data sources the component depends on.
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              description:
                type: string
        specific:
          type: object
          description: Additional metadata specific to the component.
          additionalProperties: true

    Tool:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            apiEndpoint:
              type: string
              description: API endpoint the tool interacts with.
              example: https://api.tradingtool.com/v1/execute
            inputFormat:
              type: string
              description: Expected input format (e.g., JSON, XML, CSV).
              example: JSON
            outputFormat:
              type: string
              description: Expected output format.
              example: JSON

    LLM:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            modelName:
              type: string
              description: The name of the large language model used.
              example: GPT-4
            fineTuned:
              type: boolean
              description: Whether the model has been fine-tuned for a specific task.
              example: true
            apiProvider:
              type: string
              description: Provider of the model API.
              example: OpenAI

    LocalMemory:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            storageType:
              type: string
              description: Type of memory storage (e.g., Redis, SQLite, In-Memory Cache).
              example: Redis
            persistence:
              type: boolean
              description: Whether the memory persists across agent runs.
              example: true

    Guardrail:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            enforcementLevel:
              type: string
              enum:
                - Hard
                - Soft
              description: Defines whether the rule is strictly enforced or flexible.
              example: Hard
            condition:
              type: string
              description: Business condition enforced by the guardrail.
              example: "Prevent trade execution if risk exceeds 5%"
            action:
              type: string
              description: Action taken when the guardrail is triggered (e.g., block, notify, log).
              example: "Block trade"

    Monitor:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            metricsTracked:
              type: array
              description: List of key metrics monitored.
              items:
                type: string
              example: ["Latency", "Error Rate"]
            monitoringEndpoint:
              type: string
              description: API endpoint providing monitoring data.
              example: "https://monitoring.company.com/api"

    Orchestrator:
      allOf:
        - $ref: '#/components/schemas/AgentComponent'
        - type: object
          properties:
            workflowManagement:
              type: string
              description: Defines how the orchestrator manages workflows.
              example: "State-based workflow engine"
            executionOrder:
              type: array
              description: Defines the sequence of components executed.
              items:
                type: string
              example: ["Tool", "Memory", "LLM"]
