openapi: 3.0.0
info:
  title: Agent Descriptor Specification
  description: Defines the attributes of an autonomous agent in an agentic system.
  version: 1.0.0

components:
  schemas:
    AgentDescriptor:
      type: object
      required:
        - id
        - name
        - domain
        - version
        - status
      properties:
        id:
          type: string
          description: Unique identifier for the agent.
          example: urn:agent:my_domain:my_agent:1
        name:
          type: string
          description: Human-readable name of the agent.
          example: My Trading Agent
        fullyQualifiedName:
          type: string
          description: Fully qualified name of the agent.
          example: My Trading Agent
        description:
          type: string
          description: Describes the agent’s purpose and role.
        kind:
          type: string
          description: Type of agent (e.g., decision-making, execution, monitoring).
          example: decision-making
        domain:
          type: string
          description: The domain in which the agent operates.
          example: trading
        version:
          type: string
          description: The version of the agent.
          example: 1.0.0
        environment:
          type: string
          description: Execution environment (e.g., development, production).
          example: production
        agentOwner:
          type: string
          description: The primary owner of the agent.
        agentOwnerDisplayName:
          type: string
          description: Display name of the owner.
        email:
          type: string
          description: Contact email for the agent.
          example: mailto:support@corp.com
        status:
          type: string
          description: Deployment status of the agent.
          example: ACTIVE
        capabilities:
          type: array
          description: Key functionalities of the agent.
          items:
            type: string
          example: ["DecisionMaking", "RiskManagement"]
        executionMode:
          type: string
          description: Mode of execution (e.g., autonomous, on-demand, event-driven).
          example: autonomous
        dependencies:
          type: array
          description: List of data sources or other agents this agent relies on.
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              description:
                type: string
        observability:
          type: object
          description: Monitoring and logging details.
          properties:
            healthCheck:
              type: string
              example: Automated monitoring
            decisionLogs:
              type: string
              example: Stored in event database
            anomalyDetection:
              type: string
              example: Enabled
        securityInfo:
          type: object
          description: Security and compliance details.
          properties:
            visibility:
              type: string
              example: Private
            confidentiality:
              type: string
              example: High
            gdpr:
              type: boolean
              example: true
        specific:
          type: object
          description: Any domain-specific metadata related to the agent.
          additionalProperties: true
